sudo: required
language: python
services:
- docker
python:
- '3.6'
before_script:
- docker-compose build
script:
- docker-compose run --rm web bash -c "flake8 . && python wait_for_postgres.py &&
  ./manage.py test"
after_success:
- if [ "$TRAVIS_BRANCH" == "master" ]; then docker login --username=_ --password="$HEROKU_AUTH_TOKEN"
  registry.heroku.com; docker tag web registry.heroku.com/hairutility-prod/web; docker
  push registry.heroku.com/hairutility-prod/web; fi
- if [ "$TRAVIS_BRANCH" == "qa" ]; then docker login --username=_ --password="$HEROKU_AUTH_TOKEN"
  registry.heroku.com; docker tag web registry.heroku.com/hairutility-qa/web; docker
  push registry.heroku.com/hairutility-qa/web; fi
notifications:
  email: false
cache:
  pip: true
env:
  global:
  - secure: ReSr9ECc0ROeYOgshACqjr3JAA+EHDDWTOlqlXjXv+gGjZmKPEyHS5O0Fx50dvBWp6wi+SeXgPmehZ8VW61km3lGRT5wT7Ok1m4wUmTOU1q/YEAp5I8m4bgFtHUW+bNS2WXwnpCYJni3GqvFlzKf/IPAOHzbf6IEW0SZOLnOOYpsXITh88K53DDl374aOR3LYnnbYRiSDfpl4BGxlGTPKu1BmFKYnGQcKSu6BWpSblxQGylBSt2xlP0rMrxpDn0y5tEn66lsed5eGcWKFkOPwEZt7nBGs6FHO6bXzEHVNaTENNmBSj0OhC1Fu/DRs9spyRTC20p4ikU767ke01GVIwbeF/igIbsoSRw4S5i+Kt051CAaegf6IE7CGE5xR8Z6VcEyr+UWGDm1XfVNN1BvrKTkqn8qFdXtHUlih2ulTG1iDIegQP0M2dFaSXtxbVObmii1oVCwkvqXLLMe5xhnpZdoCxmMf9yKzc7CLyV7kgDqW1Z8mE17X2idLzh3zTHNBhhxorElAApVwYwP4/H1G+NJxLK2qRWYQlHX+6Mf5Vc9DbE17xlneWA7ZhUFVOgo+CSc99omGmypjXgb3V3gnI1XOiZIEq1lCxB2ZgEEeYekwDzuiqMpdhsvSPd81VaCHioC4xByKsy39cY2FXuaytof/ZIUOOzVI6unne5NJfQ=
  - secure: owmvneBum+oMvRlkb8dFJDSElTPymZIJFjoKRGhNNMJlTY5qIkJK9/wFMUD5f82xEB6qSwmtZtxKyJBHCgxi3FUlXi1ElAUouAlEkt846surpva0kfinFWooeBdhTJIAQIzNdhNJadbM0rjhHywQIZKofYPJ2t5W7I6gNx4nrNUP66UYxDuDEb0xYrGmvpMvNKJC0bWXR7Ykk9lMziqBV+U0NMEbOJ/04rs8vRCqk5cO+RkZZVaUDUnWLJrnUggoNawU/Fz/CUaoHd1MSOOQITgXKCK+AWKHJQT8IOMnDW6H6dK7ZF5Q1ThJduIFzK49PAhw9iSDSz/mV3iyTY1HK1Hk+UaRAzRpPEDRKE0lCkLZTwCU/GVpA/IFJ4Ak5IhZE858PN7zlWdT1CY+gBVDn5gQZz6k/yoSWTQcMeCRcep6G3XqEOrqvto25rkQuJM8CrgSEYWFLBiccuZwyrBJN9q20g92QuRCrME2mGVgv6z1cOX4puZGahTgojeEqxqSXb+AFStaW8OSQrdA0zcrfl7NWLqQdV0Kqr7+jeSJxJ1DPZH8+FbYjirfI/nNZfhOjCrH20CuSfOYJ8a6QASpIWqjujSPGj/Fy6dgGvweLKTvYNcNbRDzev5bvGWdnwip9GXt5VJiPMnP7dXEtckMi9/lPYY6XsVvb4DoenS3Dm0=
  - secure: EIhEhk+rzaS/o16x1/PnT7pBKTN8gxB06H8cojzcnUoQed83Z3pcgTAb18qFPif8+mveIqqw2R9WG9jfy4b4KTigsq/8yAjPhWsjrj0x92SfMFDObT/YIMZkhyUVD8KR735AVoGzr9yoViyiIFVMnPdgQZuuJKKrIJ365JpqzBWXpFI7P64JvIdrEby0ebR6eGArysXYzndhrPSi6x9hnPfifiPyF2LkqlM3sF4j5LeKpkn5U95M+fJ8q1RK8lMsvIItXctZpZuN5uchwvrDHvK52gy5V6IymXaonOuM321K3sMYYrMUxmF+2ty6CMQGPghS4VmZicnYGgW9aR9Seo8zQwwPk+DJlG9Wyth3vqi0azP3epk8yllgRTFlHE2igIuExjAX17dXgj6JpSiZOeM2qln58LS/0SoUOYlbzxgQF6LqOnJiu3nzhZ7B8v1jn8Od9IDERPhHy7ZafbIKPrkB4cU8MDwviaQk7IIHX1YxCd2M/WfPTyiA/A/8xidxyPnkvBVLcQgFmawocY8rSXBuz8qjEmQ60ddiaybx4/mDPY1VRclynShmnjvSLySxn0GYT08LHXo6EGffVz1l4D7EqmDO9yiXydc7Pg+pMOzlQkntLIQPbly8qyPRBeqKWqXf5Rf759LAydKDLEPA986RlaoDiDU2o9qGUtt5GrE=
