version: '2'

services:
  postgres:
    image: postgres:10.5
  web:
    restart: always
    environment:
      - DJANGO_SECRET_KEY=local
    image: web
    env_file:
      - .env
    build: ./
    command: >
      bash -c "python wait_for_postgres.py &&
               ./manage.py migrate &&
               ./manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/code
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  # localstack-s3:
  #   image: localstack/localstack
  #   environment:
  #     - SERVICES=s3
  #   ports:
  #     - "4572:4572"
  #     - "8080:8080"

  # documentation:
  #   restart: always
  #   build: ./
  #   command: "mkdocs serve"
  #   volumes:
  #     - ./:/code
  #   ports:
  #     - "8001:8001"
