# Generated by Django 2.0.7 on 2018-07-29 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hairprofile',
            name='tags',
        ),
    ]
