# Generated by Django 2.0.7 on 2018-07-19 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_hairprofile_tags'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CompanyProfile',
            new_name='Company',
        ),
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Company'),
        ),
    ]
