# Generated by Django 2.0.7 on 2018-07-31 14:29

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180730_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='0000000000', max_length=128),
        ),
    ]
