# Generated by Django 2.0.7 on 2018-10-26 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_company_bio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='company',
            new_name='company_pk',
        ),
    ]
