# Generated by Django 2.0.7 on 2018-12-17 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20181026_0150'),
    ]

    operations = [
        migrations.AddField(
            model_name='hairprofile',
            name='gender',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='hairprofile',
            name='length',
            field=models.CharField(default='', max_length=6),
        ),
    ]
