# Generated by Django 2.0.7 on 2019-01-21 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20181217_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='hairprofile',
            name='thumbnail_key',
            field=models.CharField(default='', max_length=60),
        ),
    ]
