# Generated by Django 2.0.7 on 2019-01-23 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_hairprofile_thumbnail_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hairprofile',
            name='thumbnail_key',
            field=models.CharField(default='', max_length=64),
        ),
    ]
