# Generated by Django 2.0.7 on 2019-01-24 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20190123_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hairprofile',
            name='first_image_url',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='hairprofile',
            name='fourth_image_url',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='hairprofile',
            name='second_image_url',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='hairprofile',
            name='third_image_url',
            field=models.CharField(default='', max_length=200),
        ),
    ]
